### PR TITLE
fix ability to publish both publicly and privately, email us on private -> public and email author congratulations on first publish

### LINKED ISSUE #30: Bug: Once you publish privately, can't change to public?
See: https://quests.expeditiongame.com/#0B2XrUYrD8paqZHFJVFcxZkVMeXM (logged in as Fabricate)

**Notify author once fixed**

It's getting passed to quest.update, but what does that function do?

observation: It's possible that because partition is a primary key, sequelize doesn't allow UPDATEs to alter them. In which case...

1. Why does it think one already exists in the database? It should look for ID + partition and see that it doesn't exist.
2. If that's true... why isn't it creating a new entry? That would also handle the second part here, of emailing us going private -> public https://github.com/ExpeditionRPG/expedition-quest-creator/issues/358

### PR DESCRIPTION
**Pull request by toddmedema**
Closes #358
Closes #30 

The new email:
screen shot 2017-09-10 at 10 05 01 am

### CODE REVIEW

**Comment by toddmedema** [comment]
Note that this does raise a question: If an author has published both private and public versions of a quest, it's possible to overwrite both of them via a new publish, but it's not currently possible to get rid of them. I think that's still better than having a private publish default to deleting a public publish (since that seems to have been what the previous behavior was /supposed/ to do).

Related: had a good conversation with Dave about adding expedition-beta as a partition, and allowing authors to select between private, beta and public when they publish. Basically, beta = published publicly, but with a big "BETA" sticker on it

File: app/models/Quests.ts [hunk 1]
```diff
@@ -252,8 +252,24 @@ export class Quest {
...
           // If this is a newly published quest, email us!
           // We don't care if this fails.
-          const message = `Summary: ${params.summary}. By ${params.author}, for ${params.minplayers} - ${params.maxplayers} players.`;
-          Mail.send('expedition+newquest@fabricate.io', 'New quest published: ' + params.title, message);
+          Mail.send('expedition+newquest@fabricate.io',
+            'New quest published: ' + params.title,
+            `Partition: ${params.partition}. Summary: ${params.summary}. By ${params.author}, for ${params.minplayers} - ${params.maxplayers} players.`);
+
+          // If this is the author's first published quest, email them a congratulations
+          this.model.findOne({where: {userid: params.userid}})
```
Comment (smartin015) [inline app/models/Quests.ts]: This works, but it might be more appropriate to do [count](http://docs.sequelizejs.com/manual/tutorial/models-usage.html#-count-count-the-occurrences-of-elements-in-the-database) here.

File: app/models/Quests.ts [hunk 2]
```diff
@@ -252,8 +252,24 @@ export class Quest {
...
+          .then((q: QuestInstance) => {
+            if (!Boolean(q)) {
+              Mail.send([params.email,'expedition+newquest@fabricate.io'],
+                'Congratulations on publishing your first quest!',
+                `<p>${params.author},</p>
+                <p>Congratulations on publishing your first Expedition quest!</p>
+                <p>For all of the adventurers across the world, thank you for sharing your story with us - we can't wait to play it!</p>
+                <p>And remember, if you have any questions or run into any issues, please don't hesistate to email Authors@Fabricate.io</p>
```
Comment (smartin015) [inline app/models/Quests.ts]: `<a href="mailto:..."/>`?

File: app/models/Quests.ts [hunk 3]
```diff
@@ -229,7 +229,7 @@ export class Quest {
     let isNew: boolean = false;
     return this.s.authenticate()
       .then(() => {
-        return this.model.findOne({where: {id: params.id}});
+        return this.model.findOne({where: {id: params.id, partition: params.partition}});
```
Comment (smartin015) [inline app/models/Quests.ts]: Good catch!

File: app/models/Quests.ts (hunk 1 above)
Comment (toddmedema) [reply app/models/Quests.ts]: It might be slightly less intuitive, but it's faster to do findOne than counts if you're just checking for existence, since the SQL driver will stop at the first result

Comment (toddmedema) [reply app/models/Quests.ts]: `</MansplainingSQLOptimizationToGoogleEngineer>`

File: app/models/Quests.ts (hunk 2 above)
Comment (toddmedema) [reply app/models/Quests.ts]: Good call
